version: '3'
volumes:
  postgres_data: {}

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/app.DockerFile
    volumes:
      - .:/var/www/brail347a22
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./docker/web/web.DockerFile
    depends_on:
      - app
    ports:
      - 6031:80